sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
services: mongodb
install:
  - pip install "pkginfo<1.3"
  - pip install "appier==1.5.8"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
env:
  - ADAPTER=mongo
  - ADAPTER=tiny
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=appier_extras setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: dnYGdBjQu6dbRwluKTG1N2xYDKRV1j7XezDvnz0PqcsY7a7miImvpD+zcQn5n4AburJFtR5H9JBc/2DB9qsiIXsHnN/pYAxoJHxtgR05Mtw5IY+R21xztb79TyO/mUu9VVuUCAkLZzQT1McbrQ1g/ZHJcrBW+w8SEgmWmJp17jE=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
    condition: $ADAPTER = mongo
