sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - ADAPTER=mongo
  - ADAPTER=tiny
script: coverage run --source=appier_extras setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: dX8gMCc+zxVa+/IuaQPHg1mRv8jONcUONjkRJavAcfRwbAafnUB/BEFy7pG1c7HbeFkBlUAURj7n2bplps9Hel3/rvXDAwyesbIJ5N/lmelhSSQks1jKomESJDg3Ocepy+l45r5fTl+hMOGPuNOlYTBceevSs2bx9RtIfMSBS1A=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
    condition: $ADAPTER = mongo
